language: java

jdk:
  - openjdk7
  - openjdk6
  - oraclejdk7

notifications:
  recipients:
    - moorthy@nuodb.com
    - mgodekere@nuodb.com
    - bmukund@nuodb.com
    - sbushik@nuodb.com
    - plothridge@nuodb.com

before_install:
  - ./test/mysql_setup.sh
  - ./test/nuodb_setup.sh

install: mvn -U clean install

script:
  - ./test/mysql_basic.sh
  - ./test/batch_test.sh

